# src/other.yaml

seed: "0"
nruns: "1"
kingman_coal: "1"
drift_sim: "0"
msOutput: "1"
inv_freq: "0.2 0.2"
inv_age: "0"
BasesPerMorgan: "1e8"
randPhi: "0"
phi: "0.2"
invRange: "0 1e3"
fixedSNPs: "1 10 1e-6"
randSNPs: "1"
snpPositions: "1000 2000"
randomSample: "0"
tempRead: "10 0"
nCarriers: "10 0"
nCarriers1: "10 0"
nCarriers2: "10 0"
ancestor_frequencies:
  root: 0.2
